### ISSUE TITLE
Create Shop and Create Order feature

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#4]
Add feature for create shop and create order.

1. Show buttons above the home page table.
2. On clicking the button, a dialog opens in the same page and takes input from the user. Please use a div for the dialog instead of form. Using form will cause the form to be submitted whenever we hit enter on any textfield. Hence avoiding it.
3. You can use a boolean state in App.svelte to decide whether to show or hide the dialog for e.g.,
 ```
let creatingShop = false;

<button on:click={() => {creatingShop=true;}}>Add Shop</button>

{#if creatingShop}
  // show the dialog
{/if}
4. On submitting the dialog, create new shop in db.
5. Similarly do the create order flow too.
6. You can use the same dialogs later for "Edit shop" and "Edit order" feature.

**Comment by venuwiz** [comment]
While creating sample shops, choose locations within a particular city (e.g. Chennai).

To know lat,lng of a place, you can goto google maps and right click at any point and click on the lat,lng numbers in the menu. It will be copied to clipboard.

13.009324319620127, 80.25100278171082

However, trim to 7 decimal digits after pasting.

13.0093243, 80.2510027

**Comment by gopal-vsg** [comment]
Sir, I am not able to understand the second point mentioned:

"On clicking the button, a dialog opens on the same page and takes input from the user. Please use a 
 for the dialog instead of a . Using  will cause the form to be submitted whenever we hit enter on any text field, hence it should be avoided."

Could you please clarify what should be used instead of what?
![Screenshot 2024-07-19 175203](https://github.com/user-attachments/assets/5f61aec8-4caf-4570-91dd-f57244cf591b)
I'm assuming you are referring to use a div instead of form, let me know if I'm wrong.

**Comment by venuwiz** [comment]
Sorry looks like it has removed some words from the comment. I've edited the comment. You can read it again.
Basically I wanted to inform that instead of using form tag like

```
<form>
  <input type=text ... />
  <input ... />
</form>
```

you can use a div.

```
<div>
  <input ... />
  <input ... />
</div>
```

**Comment by gopal-vsg** [comment]
Created Add shop and Place order features using Daisy UI Dialog components 👍.
![image](https://github.com/user-attachments/assets/43fa94d1-db11-4ff9-8119-97ecf5fd42b7)
![image](https://github.com/user-attachments/assets/fb74063a-23d3-448e-b87a-5acec2b31402)

![image](https://github.com/user-attachments/assets/fda813a5-db4d-464b-99a0-c07673683064)
![image](https://github.com/user-attachments/assets/746ad5b6-dccb-495c-8206-9f3a5bc07ae2)
