### ISSUE TITLE
Deploy the app to vercel

### ISSUE THREAD

**Issue by venuwiz** [gopal-vsg/shopmap#9]
1. Create a vercel account (https://vercel.com/). Don't setup any deployment while creating vercel account.
2. Run `pnpm install -g vercel`
3. `cd shopmap`
4. `pnpm install`
5. `pnpm run build`
6. `vercel login` (To complete this login process, use the same browser window where you have logged into vercel.com)
7. `vercel`
    a) Follow the prompts
    b) Link to existing project - NO. So that it creates new vercel deployment project.
8. Once first setup is done and deployed, goto vercel.com and go inside the newly deployed project. It will have the app URL(something like shopmap.vercel.app)
9. Once you open the app and verify it, share that app link with me.
10. From then on, whenever you want to redeploy, run `vercel --prod` from the project directory.

**Comment by gopal-vsg** [comment]
Deployment vercel webapp : https://shopmap.vercel.app/
All the functionality works fine sir 👍
expect there is an issue⚠️ with the marker Icon of leaflet js, 
It is not showing the Icon after deployment, I'm trying to solve it, let me know if you have any solution or suggestion.

![image](https://github.com/user-attachments/assets/36a8d0aa-fc3d-4b12-9f60-4c6afa8971cc)

I also tried giving my own icon instead of the inbuilt icon, like this 
```
import L from "leaflet";
  import "leaflet/dist/leaflet.css";
  const customIcon = L.icon({
    iconUrl: "/src/assets/map-marker.png",
    iconSize: [30, 30],
    iconAnchor: [15, 30],
    popupAnchor: [0, -30],
  });
```
this change in icon is working on my local machine, but still the "no image" error in deployment

**Comment by venuwiz** [comment]
OK. I'll debug it in free time. Meanwhile you can pause investigation on this and continue working on other feature requests.

**Comment by venuwiz** [comment]
Move the map-marker.png file from src/assets/ to public/ and change code to the following. It works.

const customIcon = L.icon({
    iconUrl: "/map-marker.png",
    ...
  });

**Comment by gopal-vsg** [comment]
Icon issue resolved and deployed.
